```{r set}
#| message: false
#| include: false
library(tidyverse)
library(lubridate)
library(hms)
```

# Calibration {.unnumbered}

This chapter details all calibrations.

## Office

```{r prepo}
#| message: false
#| warning: false
err_off <- read_tsv("outputs/tomst_calib_office.tsv") %>% 
  gather(variable, value, -site, -date, -tomst_sensornum) %>% 
  group_by(site, date, variable) %>% 
  mutate(error = value - median(value))
```

```{r figohist}
#| message: false
#| warning: false
#| fig-cap: "Caption."
ggplot(err_off, aes(error)) +
  geom_histogram() +
  facet_wrap(~ variable, scales = "free") +
  theme_bw() +
  ggtitle("15 minutes errors")
```

```{r figdailyerro}
#| message: false
#| warning: false
#| fig-cap: "Caption."
err_off %>% 
  group_by(variable, site, date = as_date(date), tomst_sensornum) %>% 
  summarise(error = median(error)) %>% 
  ggplot(aes(date, error, col = as.character(tomst_sensornum))) +
  geom_line() +
  facet_wrap(~ variable, scales = "free_y") +
  theme_bw() +
  scale_color_discrete(guide = "none") +
  ggtitle("Daily median errors across days")
```

```{r figdailyerropercaptor}
#| message: false
#| warning: false
#| fig-cap: "Caption."
err_off %>% 
    mutate(tomst_sensornum = gsub("942449", "", tomst_sensornum)) %>% 
   mutate(site = str_sub(site, 1, 1)) %>% 
  group_by(variable, site, date = as_date(date), tomst_sensornum) %>% 
  summarise(error = median(error)) %>% 
  ggplot(aes(paste0(site, tomst_sensornum), error)) +
  geom_boxplot() +
  facet_wrap(~ variable, scales = "free") +
  coord_flip() +
  theme_bw() +
  theme(axis.title = element_blank())  +
  ggtitle("Daily median errors across days")
```

```{r tabo}
err_off %>% 
  group_by(variable) %>% 
  summarise(med_val = median(value),
            sd_err = sd(error),
            min_err = min(error),
            max_err = max(error),
            cv_err = sd_err/med_val*100
            ) %>% 
  knitr::kable(caption = "Caption.")
```

## Nouragues

```{r prepn}
#| message: false
#| warning: false
err_nour <- read_tsv("outputs/tomst_calib_nouragues.tsv") %>% 
  gather(variable, value, -site, -date, -tomst_sensornum) %>% 
  group_by(site, date, variable) %>% 
  mutate(error = value - median(value))
```

```{r fignhist}
#| message: false
#| warning: false
#| fig-cap: "Caption."
ggplot(err_nour, aes(error)) +
  geom_histogram() +
  facet_wrap(~ variable, scales = "free") +
  theme_bw() +
  ggtitle("15 minutes errors")
```

```{r fignhour}
#| message: false
#| warning: false
#| fig-cap: "Caption."
err_nour %>% 
  mutate(time = as_hms(date)) %>% 
  ggplot(aes(time, error, col = as.character(tomst_sensornum))) +
  geom_line(aes(group = paste(as_date(date), tomst_sensornum))) +
  facet_wrap(~ variable, scales = "free_y") +
  theme_bw() +
  scale_color_discrete(guide = "none") +
  ggtitle("15 minutes errors during the day")
```

```{r figndays}
#| message: false
#| warning: false
#| fig-cap: "Caption."
err_nour %>% 
  ggplot(aes(date, error, col = as.character(tomst_sensornum))) +
  geom_line() +
  facet_wrap(~ variable, scales = "free_y") +
  theme_bw() +
  scale_color_discrete(guide = "none") +
  ggtitle("15 minutes errors across days")
```

```{r figdailyerrnpercaptor}
#| message: false
#| warning: false
#| fig-cap: "Caption."
err_nour %>% 
  mutate(tomst_sensornum = gsub("942449", "", tomst_sensornum)) %>% 
   mutate(site = str_sub(site, 1, 1)) %>% 
  ggplot(aes(paste0(site, tomst_sensornum), error)) +
  geom_boxplot() +
  facet_wrap(~ variable, scales = "free_x") +
  coord_flip() +
  theme_bw() +
  theme(axis.title = element_blank())  +
  ggtitle("15 minutes errors across days")
```

```{r tabn}
err_nour %>% 
  group_by(variable) %>% 
  summarise(med_val = median(value),
            sd_err = sd(error),
            min_err = min(error),
            max_err = max(error),
            cv_err = sd_err/med_val*100
            ) %>% 
  knitr::kable(caption = "Caption.")
```

## Comparison

```{r figcomp}
#| message: false
#| warning: false
#| fig-cap: "Caption."
t <- err_off %>% 
  mutate(tomst_sensornum = gsub("942449", "", tomst_sensornum)) %>% 
  mutate(site = str_sub(site, 1, 1)) %>% 
  group_by(site, tomst_sensornum, variable) %>% 
  summarise(m_off = median(error), 
            l_off = quantile(error, .05), 
            h_off = quantile(error, .95))
t2 <- err_nour %>% 
  mutate(tomst_sensornum = gsub("942449", "", tomst_sensornum)) %>% 
  mutate(site = str_sub(site, 1, 1)) %>% 
  group_by(site, tomst_sensornum, variable) %>% 
  summarise(m_nour = median(error), 
            l_nour = quantile(error, .05), 
            h_nour = quantile(error, .95))
left_join(t, t2) %>%
  na.omit() %>% 
  ggplot(aes(m_off, m_nour)) +
  geom_abline(linetype = 'dashed') +
  geom_point() +
  geom_errorbar(aes(xmin = l_off, xmax = h_off), width = 0, alpha = 0.5) +
  geom_errorbar(aes(ymin = l_nour, ymax = h_nour), width = 0, alpha = 0.5) +
  theme_bw() +
  geom_smooth(method = "lm", se = F) +
  ggpubr::stat_cor()
```
