```{r setup}
#| message: false
#| include: false
library(tidyverse)
```

# Indices {.unnumbered}

This chapter details all indices building.

-   [BIOCLIM](https://www.worldclim.org/data/bioclim.html) indices
    -   BIO1 = Annual Mean Temperature
    -   BIO2 = Mean Diurnal Range (Mean of monthly (max temp - min temp))
    -   BIO3 = Isothermality (BIO2/BIO7) (×100)
    -   BIO4 = Temperature Seasonality (standard deviation ×100)
    -   BIO5 = Max Temperature of Warmest Month
    -   BIO6 = Min Temperature of Coldest Month
    -   BIO7 = Temperature Annual Range (BIO5-BIO6)
    -   BIO8 = Mean Temperature of Wettest Quarter
    -   BIO9 = Mean Temperature of Driest Quarter
    -   BIO10 = Mean Temperature of Warmest Quarter
    -   BIO11 = Mean Temperature of Coldest Quarter
    -   BIO12 = Annual Precipitation
    -   ~~BIO13 = Precipitation of Wettest Month~~
    -   ~~BIO14 = Precipitation of Driest Month~~
    -   ~~BIO15 = Precipitation Seasonality (Coefficient of Variation)~~
    -   ~~BIO16 = Precipitation of Wettest Quarter~~
    -   ~~BIO17 = Precipitation of Driest Quarter~~
    -   ~~BIO18 = Precipitation of Warmest Quarter~~
    -   ~~BIO19 = Precipitation of Coldest Quarter~~
    -   To be adapted to each temperature measurement
    -   *Replace precipitation with soil water content?*
-   [Extreme events 27](https://etccdi.pacificclimate.org/list_27_indices.shtml)
    -   TX_x: Monthly maximum value of daily maximum temperature
    -   ~~TN_x: Monthly maximum value of daily minimum temperature~~
    -   TX_n: Monthly minimum value of daily maximum temperature
    -   ~~TN_n: Monthly minimum value of daily minimum temperature~~
    -   ~~TN10p: Percentage of days when TN \< 10th percentile~~
    -   TX10p: Percentage of days when TX \< 10th percentile
    -   ~~TN90p: Percentage of days when TN \> 90th percentile~~
    -   TX90p: Percentage of days when TX \> 90th percentile
    -   WSDI, Warm speel duration index: Annual count of days with at least 6 consecutive days when TX \> 90th percentile
    -   ~~CSDI, Cold speel duration index: Annual count of days with at least 6 consecutive days when TN \< 10th percentile~~
    -   DTR, Daily temperature range: Monthly mean difference between TX and TN
    -   To be adapted to each temperature measurement
    -   *Replace precipitation with soil water content?*
-   Time periods:
    -   Dial / Nocturnal
    -   Day
    -   Month
    -   Season (Dry / Wet)
    -   Year
