```{r set}
#| message: false
#| include: false
library(tidyverse)
```

# Guyaflux {.unnumbered}

@bonal2008

```{r guyaflux}
#| message: false
#| warning: false
#| fig-cap: "Guyaflux raw data"
readxl::read_excel("data/raw_data/guyaflux/TourAFlux-2023-2024.xlsx", 
                               sheet = "Gx meteo_2023-2024",
                               col_types = c("date", rep("numeric", 29))) %>% 
  rename_all(tolower) %>% 
  rename(tas_55 = `temp(55)`, hr_55 = `hr(55)`, tas_2 = `temp(2,0)`, hr_2 = `hr(2,0)`, 
         ts_0.1 = t_avg_10cm, 
         swc_0.1 = vwc_avg_10cm, swc_0.2 = vwc_avg_20cm, 
         swc_0.8 = vwc_avg_80cm, swc_1.4 = vwc_avg_140cm, 
         swc_1.9 = vwc_avg_190cm, 
         snet = rg, 
         ws = `vit vent`, pr = pluie) %>% 
  select(date, tas_55, hr_55, tas_2, hr_2, ts_0.1, 
         swc_0.1,swc_0.2, swc_0.8, swc_1.4, swc_1.9, 
         snet, ws, pr) %>% 
  gather(variable, value, -date) %>% 
  ggplot(aes(date, value)) +
  geom_rect(xmin = as_datetime("2023-8-1 00:00:00"), 
            xmax = as_datetime("2023-12-1 00:00:00"), 
            ymin = -Inf, ymax = Inf, alpha = 0.5, fill  = "#fff4e0") +
  geom_line(col = "lightgrey", alpha = 0.5) +
  geom_smooth() +
  facet_wrap(~ variable, scales = "free_y") +
  theme_bw() +
  theme(axis.title = element_blank(), axis.text.x = element_text(angle = 90))
```

> This is the extracted data for 2023-2024 but more data might be requested to Damien Bonal and Benoit Burbant.
