# Introduction {.unnumbered}

**microclim** is a sub-project of the first article from Vincyan Badouard's PhD with the following question:

> Are air temperature and soil moisture linked to canopy openness and topography?

The objective are:

-   Data cleaning
-   Spatio-temporal exploration of the data
-   Choice and computation of metrics

## Project

**microclim** includes all codes to access the data (in `data/`) & analyse the data (`files.qmd`) with associated [documentation and figures](https://sylvainschmitt.github.io/microclim/). Intermediary files and outputs can be accessed in `outputs/`. The project takes advantage of `renv` to manage the R environment for enhanced reproducibility.

## Contribution

You can contribute to the project by forking the repository on github and cloning the fork to your machine using several options, including GitHub desktop GUI. Access to the data is limited and can be requested by emailing people from the core group (see below). Further informations on contribution are detailed in the online document: <https://sylvainschmitt.github.io/microclim/98_contributing.html>.

## Help

Please preferentially create an issue on GitHub for any questions, bugs or help needed regarding **microclim**: [https://github.com/sylvainschmitt/microclim/issues](https://github.com/Bsylvainschmitt/microclim/issues){.uri} . You may however reach us by mail with people from the core group (see below).

## Core group

-   Sylvain Schmitt (sylvain.schmitt\@cirad.fr)

-   Vincyane Badouard (vincyane.badouard\@gmail.com)

-   Géraldine Derroire (geraldin.derroire\@cirad.fr)

-   Grégoire Vincent (gregoire.vincent\@ird.fr)

-   Éric Marcon (eric.marcon\@agroparistech.fr)
